/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.SystemAdminWorkArea;

import DAO.ManageAdminDAO;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author SHREE GANESH
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel container;
    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    public SystemAdminWorkAreaJPanel(JPanel container) {
        initComponents();
        this.container = container;
        populateTree();
    }
    

    public void populateTree(){
        DefaultTreeModel model=(DefaultTreeModel)jtreeNetwork.getModel();
        //jtreeNetwork.setShowsRootHandles(true);
        DefaultMutableTreeNode networks=new DefaultMutableTreeNode("Networks");
        DefaultMutableTreeNode root=(DefaultMutableTreeNode)model.getRoot();
        root.removeAllChildren();
        root.insert(networks, 0);
        
        ArrayList<String> networkList = ManageAdminDAO.selectNetwork();
       
        DefaultMutableTreeNode networkNode;
        DefaultMutableTreeNode enterpriseNode;
        DefaultMutableTreeNode organizationNode;
        
        for(int i=0;i<networkList.size();i++){
            networkNode=new DefaultMutableTreeNode(networkList.get(i));
            networks.insert(networkNode, i);
            ArrayList<String> enterpriseList = ManageAdminDAO.selectEnterprise(networkList.get(i));
            for(int j=0; j<enterpriseList.size();j++){
                enterpriseNode=new DefaultMutableTreeNode(enterpriseList.get(j));
                networkNode.insert(enterpriseNode, j);
                ArrayList<String> organizationList = ManageAdminDAO.selectOrganization(enterpriseList.get(j));
                for(int k=0;k<organizationList.size();k++){
                    organizationNode=new DefaultMutableTreeNode(organizationList.get(i));
                    enterpriseNode.insert(organizationNode, k);
                }
                
            }
            
            
        }
        model.reload();
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageNetwork = new javax.swing.JButton();
        btnManageEnterprise = new javax.swing.JButton();
        btnManageAdmin = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtreeNetwork = new javax.swing.JTree();

        setBackground(new java.awt.Color(255, 204, 255));

        btnManageNetwork.setBackground(new java.awt.Color(255, 51, 102));
        btnManageNetwork.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 12)); // NOI18N
        btnManageNetwork.setForeground(new java.awt.Color(255, 204, 255));
        btnManageNetwork.setText("Manage Network");
        btnManageNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageNetworkActionPerformed(evt);
            }
        });

        btnManageEnterprise.setBackground(new java.awt.Color(255, 51, 102));
        btnManageEnterprise.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 12)); // NOI18N
        btnManageEnterprise.setForeground(new java.awt.Color(255, 204, 255));
        btnManageEnterprise.setText("Manage Enterprise");
        btnManageEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEnterpriseActionPerformed(evt);
            }
        });

        btnManageAdmin.setBackground(new java.awt.Color(255, 51, 102));
        btnManageAdmin.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 12)); // NOI18N
        btnManageAdmin.setForeground(new java.awt.Color(255, 204, 255));
        btnManageAdmin.setText("Manage Enterprise Admin");
        btnManageAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAdminActionPerformed(evt);
            }
        });

        jtreeNetwork.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jScrollPane1.setViewportView(jtreeNetwork);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnManageEnterprise, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnManageNetwork, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnManageAdmin, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnManageNetwork)
                .addGap(18, 18, 18)
                .addComponent(btnManageEnterprise)
                .addGap(18, 18, 18)
                .addComponent(btnManageAdmin)
                .addContainerGap(170, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageNetworkActionPerformed

          CardLayout layout = (CardLayout) container.getLayout();
            ManageNetworkJPanel manageNetworkPanel = new ManageNetworkJPanel(container);
            container.add("ManageNetworkJPanel", manageNetworkPanel);
            layout.next(container);
          
    }//GEN-LAST:event_btnManageNetworkActionPerformed

    private void btnManageEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEnterpriseActionPerformed
            CardLayout layout = (CardLayout) container.getLayout();
            ManageEnterpriseJPanel manageEntpsPanel = new ManageEnterpriseJPanel(container);
            container.add("ManageEnterpriseJPanel", manageEntpsPanel);
            layout.next(container);
    }//GEN-LAST:event_btnManageEnterpriseActionPerformed

    private void btnManageAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAdminActionPerformed
       CardLayout layout = (CardLayout) container.getLayout();
            ManageEnterpriseUsersJPanel manageEntpsUsersPanel = new ManageEnterpriseUsersJPanel(container);
            container.add("ManageEnterpriseJPanel", manageEntpsUsersPanel);
            layout.next(container);
    }//GEN-LAST:event_btnManageAdminActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageAdmin;
    private javax.swing.JButton btnManageEnterprise;
    private javax.swing.JButton btnManageNetwork;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jtreeNetwork;
    // End of variables declaration//GEN-END:variables
}
