/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.AdminUserDTO;
import DAO.ManageAdminDAO;
import DAO.ProcessDao;
import Services.EmailService;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ABC
 */
public class RegisterScreenJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegisterScreenJPanel
     */
    JPanel container;
    public RegisterScreenJPanel(JPanel container) {
        initComponents();
        this.container = container;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TextFieldUserName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TextPassword = new javax.swing.JPasswordField();
        ButtonRegister = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        TextFieldaddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TextFieldPhnNo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TextFieldEmailId = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TextFieldCity = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TextFieldState = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TextFieldCountry = new javax.swing.JTextField();
        errUserName = new javax.swing.JLabel();
        errAddress = new javax.swing.JLabel();
        errPassword = new javax.swing.JLabel();
        errPhone = new javax.swing.JLabel();
        errEmail = new javax.swing.JLabel();
        errCity = new javax.swing.JLabel();
        errState = new javax.swing.JLabel();
        errCountry = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Role Registration");

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 255, 204));
        jLabel3.setText("User Name:");

        TextFieldUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldUserNameActionPerformed(evt);
            }
        });
        TextFieldUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextFieldUserNameKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 255, 204));
        jLabel4.setText("Password: ");

        TextPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPasswordActionPerformed(evt);
            }
        });
        TextPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextPasswordKeyReleased(evt);
            }
        });

        ButtonRegister.setBackground(new java.awt.Color(255, 0, 51));
        ButtonRegister.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        ButtonRegister.setForeground(new java.awt.Color(255, 204, 204));
        ButtonRegister.setText("Register");
        ButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRegisterActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 255, 204));
        jLabel5.setText("Address:");

        TextFieldaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldaddressActionPerformed(evt);
            }
        });
        TextFieldaddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextFieldaddressKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 255, 204));
        jLabel6.setText("Phone No:");

        TextFieldPhnNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextFieldPhnNoKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 255, 204));
        jLabel7.setText("Email ID:");

        TextFieldEmailId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldEmailIdActionPerformed(evt);
            }
        });
        TextFieldEmailId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextFieldEmailIdKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 255, 204));
        jLabel8.setText("City:");

        TextFieldCity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextFieldCityKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 255, 204));
        jLabel9.setText("State: ");

        TextFieldState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldStateActionPerformed(evt);
            }
        });
        TextFieldState.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextFieldStateKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 255, 204));
        jLabel10.setText("Country:");

        TextFieldCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldCountryActionPerformed(evt);
            }
        });
        TextFieldCountry.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextFieldCountryKeyReleased(evt);
            }
        });

        errUserName.setFont(new java.awt.Font("Bodoni MT", 0, 10)); // NOI18N
        errUserName.setForeground(new java.awt.Color(255, 153, 255));

        errAddress.setFont(new java.awt.Font("Bodoni MT", 0, 10)); // NOI18N
        errAddress.setForeground(new java.awt.Color(255, 153, 255));
        errAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                errAddressKeyReleased(evt);
            }
        });

        errPassword.setFont(new java.awt.Font("Bodoni MT", 0, 10)); // NOI18N
        errPassword.setForeground(new java.awt.Color(255, 153, 255));

        errPhone.setFont(new java.awt.Font("Bodoni MT", 0, 10)); // NOI18N
        errPhone.setForeground(new java.awt.Color(255, 153, 255));
        errPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                errPhoneKeyReleased(evt);
            }
        });

        errEmail.setFont(new java.awt.Font("Bodoni MT", 0, 10)); // NOI18N
        errEmail.setForeground(new java.awt.Color(255, 153, 255));
        errEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                errEmailKeyReleased(evt);
            }
        });

        errCity.setFont(new java.awt.Font("Bodoni MT", 0, 10)); // NOI18N
        errCity.setForeground(new java.awt.Color(255, 153, 255));
        errCity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                errCityKeyReleased(evt);
            }
        });

        errState.setFont(new java.awt.Font("Bodoni MT", 0, 10)); // NOI18N
        errState.setForeground(new java.awt.Color(255, 153, 255));
        errState.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                errStateKeyReleased(evt);
            }
        });

        errCountry.setFont(new java.awt.Font("Bodoni MT", 0, 10)); // NOI18N
        errCountry.setForeground(new java.awt.Color(255, 153, 255));
        errCountry.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                errCountryKeyReleased(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(255, 0, 51));
        btnBack.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 204, 204));
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(ButtonRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextFieldUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                    .addComponent(TextPassword)
                                    .addComponent(TextFieldaddress)
                                    .addComponent(TextFieldPhnNo)
                                    .addComponent(TextFieldEmailId)
                                    .addComponent(TextFieldCity)
                                    .addComponent(TextFieldState)
                                    .addComponent(TextFieldCountry))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(errUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(errAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(errPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(errEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(errCity, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(errState, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(errCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(errPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(errUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(errPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TextFieldaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TextFieldPhnNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(errPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TextFieldEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(errEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addComponent(errCity, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(TextFieldCity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9)
                    .addComponent(errState, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(TextFieldState))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(TextFieldCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonRegister)
                    .addComponent(btnBack))
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldUserNameActionPerformed
        
       
        
    }//GEN-LAST:event_TextFieldUserNameActionPerformed

    private void ButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRegisterActionPerformed
        // TODO add your handling code here:
        
        // User input collection and validation
        //String roleName = RoleNameComboBox.getSelectedItem().toString();
        
        String userName = TextFieldUserName.getText();
        String password = TextPassword.getText();
        String address = TextFieldaddress.getText();
        String phnNo = TextFieldPhnNo.getText();
        String email = TextFieldEmailId.getText();
        String city = TextFieldCity.getText();
        String state = TextFieldState.getText();
        String country = TextFieldCountry.getText();
        
        //AdminUserDTO donorObj = new AdminUserDTO(userName, password, email, phnNo, 'NA', 'NA', 'NA',  city, state);
       if(Validation.checkAlphaNumeric(userName) && Validation.checkAlphaNumericSpecial(password) && Validation.checkMultiAlphaNumericSpecial(address) && Validation.checkPhoneNo(phnNo) && Validation.checkEmailId(email) && Validation.checkAlpha(city) && Validation.checkAlpha(state) && Validation.checkAlpha(country)){
        AdminUserDTO donorObj = new AdminUserDTO();
        donorObj.setUserName(userName);
        donorObj.setPassword(password);
        donorObj.setAddress(address);
        donorObj.setPhoneNo(phnNo);
        donorObj.setEmailId(email);
        donorObj.setCity(city);
        donorObj.setState(state);
        donorObj.setCountry(country);
        //ProcessDao pDao = new ProcessDao();
        //pDao.createUser(roleName, userName, password, address, phnNo, email, city,state, country);
        
        ManageAdminDAO dao = new ManageAdminDAO();
        ManageAdminDAO.insertDonorUser(donorObj);
        
        JOptionPane.showMessageDialog(null, "User Registered as DONOR successfully !!", "Info", JOptionPane.INFORMATION_MESSAGE);
        String subject = "Thanks for registering with us";
        String message = "Please login with your username: " + userName + " to donate or remove books, wood trash or any other paper waste";  
        
        EmailService.email(email,subject,message);
       }else{
       JOptionPane.showMessageDialog(null, "Please Enter Correct Details !!", "Warning", JOptionPane.WARNING_MESSAGE);
       }
    }//GEN-LAST:event_ButtonRegisterActionPerformed

    private void TextFieldaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldaddressActionPerformed

    private void TextFieldStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldStateActionPerformed

    private void TextFieldCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldCountryActionPerformed

    private void TextFieldUserNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldUserNameKeyReleased
        // TODO add your handling code here:
         if(!Validation.checkAlphaNumeric(TextFieldUserName.getText())){
        errUserName.setText("Use only letters and numbers");
        
        }else{
        errUserName.setText("");
        }
    }//GEN-LAST:event_TextFieldUserNameKeyReleased

    private void TextPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextPasswordKeyReleased
        if(!Validation.checkAlphaNumericSpecial(TextPassword.getText())){
        errPassword.setText("Use only letters, numbers & special chars");
        
        }else{
        errPassword.setText("");
        }
    }//GEN-LAST:event_TextPasswordKeyReleased

    private void errAddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_errAddressKeyReleased
       
    }//GEN-LAST:event_errAddressKeyReleased

    private void errPhoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_errPhoneKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_errPhoneKeyReleased

    private void errEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_errEmailKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_errEmailKeyReleased

    private void errCityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_errCityKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_errCityKeyReleased

    private void errStateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_errStateKeyReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_errStateKeyReleased

    private void errCountryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_errCountryKeyReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_errCountryKeyReleased

    private void TextPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPasswordActionPerformed

    private void TextFieldaddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldaddressKeyReleased
        // TODO add your handling code here:
         if(!Validation.checkMultiAlphaNumericSpecial(TextFieldaddress.getText())){
        errAddress.setText("Enter valid address");
        
        }else{
        errAddress.setText("");
        }
        
    }//GEN-LAST:event_TextFieldaddressKeyReleased

    private void TextFieldPhnNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldPhnNoKeyReleased
        // TODO add your handling code here:
        if(!Validation.checkPhoneNo(TextFieldPhnNo.getText())){
        errPhone.setText("Incorrect Phone number");
        
        }else{
        errPhone.setText("");
        }
    }//GEN-LAST:event_TextFieldPhnNoKeyReleased

    private void TextFieldEmailIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldEmailIdKeyReleased
        // TODO add your handling code here:
        if(!Validation.checkEmailId(TextFieldEmailId.getText())){
        errEmail.setText("Incorrect Email ID");
        
        }else{
        errEmail.setText("");
        }
    }//GEN-LAST:event_TextFieldEmailIdKeyReleased

    private void TextFieldCityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldCityKeyReleased
        // TODO add your handling code here:
        if(!Validation.checkAlpha(TextFieldCity.getText())){
        errCity.setText("Enter proper City name");
        
        }else{
        errCity.setText("");
        }
    }//GEN-LAST:event_TextFieldCityKeyReleased

    private void TextFieldStateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldStateKeyReleased
        // TODO add your handling code here:
         if(!Validation.checkAlpha(TextFieldState.getText())){
        errState.setText("Enter proper state name");
        
        }else{
        errState.setText("");
        }
    }//GEN-LAST:event_TextFieldStateKeyReleased

    private void TextFieldCountryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldCountryKeyReleased
        // TODO add your handling code here:
         if(!Validation.checkAlpha(TextFieldCountry.getText())){
        errCountry.setText("Incorrect country");
        
        }else{
        errCountry.setText("");
        }
    }//GEN-LAST:event_TextFieldCountryKeyReleased

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed

    private void TextFieldEmailIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldEmailIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldEmailIdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonRegister;
    private javax.swing.JTextField TextFieldCity;
    private javax.swing.JTextField TextFieldCountry;
    private javax.swing.JTextField TextFieldEmailId;
    private javax.swing.JTextField TextFieldPhnNo;
    private javax.swing.JTextField TextFieldState;
    private javax.swing.JTextField TextFieldUserName;
    private javax.swing.JTextField TextFieldaddress;
    private javax.swing.JPasswordField TextPassword;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel errAddress;
    private javax.swing.JLabel errCity;
    private javax.swing.JLabel errCountry;
    private javax.swing.JLabel errEmail;
    private javax.swing.JLabel errPassword;
    private javax.swing.JLabel errPhone;
    private javax.swing.JLabel errState;
    private javax.swing.JLabel errUserName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
